name: fish_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  font_awesome_flutter: ^10.1.0
  collection: ^1.18.0
  url_launcher: ^6.0.0 
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/fish/
    - assets/images/crab/
    - assets/images/shellfish/
    - assets/images/squid/
    - assets/images/shrimp/
    - assets/images/gcash/  # Add this line to include the GCash images directory
    - assets/images/logo/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo/mabini_fish_app_logo(1).png
  min_sdk_android: 21

flutter_native_splash:
  image: assets/images/logo/mabini_fish_app_logo.png
  color: "#0800FF"
